# Generated by Django 4.1.2 on 2022-10-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_tutortoken_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='is_tutor',
            field=models.BooleanField(default=True),
        ),
    ]
