# Generated by Django 4.1.2 on 2022-10-27 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_rename_teacher_id_teachertoken_tutor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
