# Generated by Django 4.1.2 on 2022-10-27 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_teacher_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/teachers_dp/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technology',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='dp',
            field=models.ImageField(blank=True, upload_to='photos/teachers_dp/'),
        ),
    ]
