# Generated by Django 4.1.2 on 2022-11-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0013_alter_teacher_email_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_Paid',
            field=models.BooleanField(default=False),
        ),
    ]
