# Generated by Django 4.1.2 on 2022-11-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0015_alter_coursecategory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='material_1',
            field=models.FileField(blank=True, upload_to='material_1/chapter/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='material_2',
            field=models.ImageField(blank=True, upload_to='material_2/chapter/'),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='is_addded',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
