# Generated by Django 4.1.2 on 2022-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0016_chapter_material_1_chapter_material_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
