# Generated by Django 4.1.2 on 2022-11-08 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0019_rename_title_chapter_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='heading',
            new_name='title',
        ),
    ]
