# Generated by Django 4.1.2 on 2022-11-09 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0020_rename_heading_chapter_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecategory',
            old_name='is_addded',
            new_name='is_added',
        ),
    ]
