# Generated by Django 4.1.2 on 2022-11-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0022_assignments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignments',
            name='assignment_file',
            field=models.FileField(upload_to='assignment/chapter/'),
        ),
    ]
