# Generated by Django 4.1.2 on 2022-11-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0023_alter_assignments_assignment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignments',
            options={'verbose_name_plural': '5. Assignments'},
        ),
    ]
