# Generated by Django 4.1.2 on 2022-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0026_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_no',
            field=models.IntegerField(null=True),
        ),
    ]
