# Generated by Django 4.1.2 on 2022-11-23 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0028_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField(default=True)),
                ('course', models.CharField(max_length=255, null=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '10.Certificate',
            },
        ),
        migrations.CreateModel(
            name='PostCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercertificate', models.FileField(upload_to='user/certificate')),
                ('success', models.BooleanField(default=True)),
                ('course', models.IntegerField(null=True)),
                ('certicate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.certificate')),
            ],
            options={
                'verbose_name_plural': '11.postCertificate',
            },
        ),
    ]
