# Generated by Django 4.1.2 on 2022-11-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0030_userassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassignment',
            name='chaptername',
        ),
        migrations.AddField(
            model_name='userassignment',
            name='coursename',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='tutor.course'),
            preserve_default=False,
        ),
    ]
