# Generated by Django 4.1.2 on 2022-11-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0031_remove_userassignment_chaptername_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userassignment',
            options={'verbose_name_plural': '9.User Assignments'},
        ),
        migrations.AlterField(
            model_name='userassignment',
            name='userassignment',
            field=models.FileField(null=True, upload_to='user/assignments'),
        ),
    ]
