# Generated by Django 4.1.2 on 2022-11-24 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0032_alter_userassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuizAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('answer', models.CharField(max_length=200)),
                ('QuizQuestions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.quizquestions')),
                ('studentname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '8.User Quiz Answer Sheet',
            },
        ),
        migrations.DeleteModel(
            name='CourseQuiz',
        ),
    ]
